theme: jekyll-theme-architect
title: MathPi 
description: Resource Archive for CUHK-Shenzhen

# This helps your math formulas render if you use them later
markdown: kramdown
highlighter: rouge

header_pages:
  - index.md
  - exams.md
  - notes.md
  - activities.md